pykeepass/pykeepass.py

Apps using this library should configure logging however
they want, and not have pykeepass try to do it when they
import pykeepass
Fixes issue #3

Remove main library import logging configuration/setup

---

pykeepass/entry.py

In order to bypass https://github.com/pschmitt/pykeepass/issues/14 we
set expires to False. This allows faulty versions of KeePassX to open
files with passwords added by pykeepass.

Set expires parameter to False by default

---

README.rst

The README mentions `find_entry_by_name` which has been replaced by `find_entry_by_title`.

Small update of the README.

---

.gitignore
pykeepass/pykeepass.py
tests/tests.py

dump_xml returns bytes, so we need to add 'b' to file mode
```
Traceback (most recent call last):
File "tests/tests.py", line 230, in test_dump_xml
self.kp.dump_xml('db_dump')
File "/home/evan/resources/pykeepass/pykeepass/pykeepass.py", line 81, in dump_xml
f.write(self.kdb.pretty_print())
TypeError: write() argument must be str, not bytes
```

fix dump_xml on python3

---

pykeepass/baseelement.py
pykeepass/entry.py
pykeepass/group.py

Changed it so that `BaseElement.__init__` is only called when `element` is None in `Group` and `Entry`.

fix baseelement logic

---

README.rst
pykeepass/pykeepass.py
tests/tests.py

A small patch so we can use `with` statements. Maybe it's no use to you if you're deprecating libkeepass /shrug

Make PyKeePass usable as a context manager

---

pykeepass/kdbx_parsing/common.py

Decryption: Strip out not allowed characters

---

pykeepass/entry.py

Not sure if this is the right way to fix this issue but it solved my problem with python2 and python3. maybe there's a way to tell lxml to create the attributes when loading the file.

fix "object has no attribute" issue in save_history

---

pykeepass/baseelement.py
pykeepass/entry.py
setup.py
tests/tests.py

Resolves issues: https://github.com/pschmitt/pykeepass/issues/115 and https://github.com/pschmitt/pykeepass/issues/117

Fix datetime comparison when there is no tzinfo and autotype sequence none check

---

.travis.yml

cf. https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
and https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Remove "sudo" tag as it is deprecated

---

pykeepass/entry.py
tests/tests.py

The property `autotype_sequence` was not returning a value when a value was clearly visible using dump_xml() or viewing the autotype sequence in KeepassXC. This PR should fix that problem. All tests still pass. Included one small related PEP8 fix as well. Thanks!

Autotype property fix

---

pykeepass/entry.py

It is added to the reserved_keys global so it does not show in the
Entry.custom_properties property

Notes is a reserved key

---

README.rst
pykeepass/pykeepass.py
tests/tests.py

This is what I proposed in #127.  It also fixes a bug where `find_entries('foobar_group/sub_group/', first=True)` could return a `Group` instead of an `Entry`.

Make 'path' ignore other arguments.

---

pykeepass/entry.py
pykeepass/pykeepass.py
requirements.txt
setup.py
tests/tests.py

I inspected a kdbx created by KeePass, and found that /KeePassFile/Meta/Binaries/Binary requires an ID key to reference the proper data, and fixed a `data = base64.b64encode(data).decode` typo which was not decoding the data.
See https://github.com/pschmitt/pykeepass/issues/146#issue-421943414 for debug details

Fix <= version (4,0) ~version 3 add_binary ID referencing

---

pykeepass/pykeepass.py

as described in https://github.com/libkeepass/pykeepass/issues/171
the function find_groups_by_path was defined twice. the first was wrong and that's what VS Code marked as a problem. the second definition was correct and that's why the tests ran through without problems.
So, I deleted the first definition to keep the code nice and clean

deleted wrong definition of find_groups_by_path

---

pykeepass/baseelement.py

I noticed the following
KDBX V3
```
>>> from pykeepass import PyKeePass
>>> database = 'test3.kdbx'
>>> password = 'password'
>>> keyfile = 'test3.key'
>>> kp = PyKeePass(database, password=password, keyfile=keyfile)
>>> 
>>> from datetime import datetime, timedelta
>>> from dateutil import tz
>>> from pykeepass.entry import Entry
>>> now = datetime.now(tz.gettz())
>>> utc = datetime.now(tz.gettz('UTC'))
>>> entry = Entry(
...     'title',
...     'username',
...     'password',
...     kp=kp
... )
>>> 
>>> now
datetime.datetime(2019, 9, 20, 9, 23, 40, 885385, tzinfo=tzfile('/etc/localtime'))
>>> utc
datetime.datetime(2019, 9, 20, 7, 23, 40, 885720, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))
>>> entry.atime
datetime.datetime(2019, 9, 20, 5, 23, 40, 886515, …
```

make sure timestamps are not converted twice to UTC

---

pykeepass/entry.py
tests/tests.py

https://github.com/libkeepass/pykeepass/issues/120 is open for some time and I almost forgot about it
here's another try to get this fixed
I made 2 changes:
- I changed the code for the touch function to use the atime.setter/mtime.setter from the BaseElement class
- I added a test in the EntryTests class to test the touch function. Sorry for the sleep statement but I had no better idea
Hope this helps
BoomerB

changed entry.touch() to use member functions to change atime/mtime

---

pykeepass/pykeepass.py

Initialization will overwrite other project calls to logging basicConfig

Remove logging initialization with default values

---

doc/Makefile
doc/make.bat
doc/source/attachment.rst
doc/source/baseelement.rst
doc/source/conf.py
doc/source/entry.rst
doc/source/exceptions.rst
doc/source/group.rst
doc/source/icons.rst
doc/source/index.rst
doc/source/kdbx_parsing/common.rst
doc/source/kdbx_parsing/kdbx.rst
doc/source/kdbx_parsing/kdbx3.rst
doc/source/kdbx_parsing/kdbx4.rst
doc/source/kdbx_parsing/pytwofish.rst
doc/source/kdbx_parsing/twofish.rst
doc/source/pykeepass.rst
requirements-rtd.txt

Copies README.rst + adds basic structure + `automodule` for each module except `xpath` (seems like a file with constants only).
Documentation is here: https://pykeepass.readthedocs.io/en/latest/, currently built from my `rtd` branch. Create accounts on RTD so I can give you maintainer access. :yum: 
Closes #111

Add documentation to ReadTheDocs

---

README.rst
doc/source/index.rst

For IRC it also gives an online client provided directly by Freenode so there's no need to install anything (same as with Matrix).

Add badges for IRC channel and RTD build status

---

pykeepass/kdbx_parsing/kdbx3.py

The official KeePass client produces and expects a 64 bit field, not a
32 bit field, for this parameter.
Using the incorrect length happens to parse just fine. The correct
length is encoded into the header so there is no parsing misalignment.
And because the field is little endian, parsing the field itself as a 32
bit field even though it is actually a 64 bit field also works, provided
that the field value fits into 32 bits, which it typically does.
However, if we write header field back out, we write it with a 32 bit
length, and KeePass rejects this. We weren't writing out the header
ourselves previously because kdbx.header.data wasn't being removed (see
https://github.com/libkeepass/pykeepass/issues/219#issuecomment-748692045).
However if we start doing that, such as to fix issue #219, …

kdbx3: fix length of transform_rounds field

---

setup.py

We are experiencing some conflicts due to the pykeepass pypi-dist-package not just containing the "pykeepass" python package but also the "tests" package.
With this small fix, the dist/wheel will not contain the tests package.

Fix for setup.py, currently the dist package contains not just the pykeepass package but also the tests

---

pykeepass/entry.py
tests/tests.py

**Issue:** When adding a new entry, it sets the autotype_sequence to 'None' (as a string). 
**Proposed solution:** Checks on both autotype_sequence initializer and getter if the element is None or equal to ''.
Closes #284

Set autotype_sequence to None when adding entry

---

pykeepass/entry.py
tests/tests.py

In Secrets we want to present protected custom properties with hidden text, so we need a way to query whether an attribute is protected.
My knowledge of lxml is just what you can see in the PR, so please tell me if there is a better way to achieve this.
See https://gitlab.gnome.org/World/secrets/-/merge_requests/721, specifically https://gitlab.gnome.org/World/secrets/-/merge_requests/721/diffs#234455d6642dc1a00aa62f6a0b9581fc403591c1_611_615 where we use this ~~hack~~ *method*.

entry: Add is_custom_property_protected method

---

pykeepass/kdbx_parsing/pytwofish.py

Since the explicitly little-endian `struct` format strings are already handling byte-swapping, remove the `WORD_BIGENDIAN` flag and all of the excessive byte-swapping it enables.
Fixes #332.

Remove excessive byte-swapping in pytwofish.py

---

pykeepass/entry.py

When doing:
```python
kp.add_entry(kp.root_group, "title", "username", "password", otp="otpauth://")
```
The OTP will not be marked as protected, while this will be:
```python
entry = kp.add_entry(kp.root_group, "title", "username", "password")
entry.otp = "otpauth://"
```
This PR fixes `add_entry()` otp to be protected, in line with the property (and other clients).
(I did look into writing a unit test, but it looks like there's no way to know if the core properties are protected.  `is_custom_property_protected("otp")` will not work.)

add_entry(): Make otp= protected

---

pykeepass/baseelement.py
pykeepass/entry.py
tests/tests.py

- Allows for e.g. set() which uses hash() for deduplication
- Consider mtime for HistoryEntry equality
- Additional unit tests

Use __hash__ for BaseElement

---

pykeepass/attachment.py
pykeepass/baseelement.py
pykeepass/entry.py
pykeepass/group.py
pykeepass/pykeepass.py
pykeepass/xpath.py
requirements-rtd.txt
requirements.txt
setup.py
tests/tests.py

I have removed all the future imports, and also I have removed the parent class of object since that was a workaround needed for Python2.
By the way:
`construct` just dropped the support, dropping tests and etc in https://github.com/construct/construct/commit/52c7cd23933d83922a289112a7c01dad7ffde5a3 (which is version 2.10.54) but it has been updated (several times) for some reason.

Depecrate Python2

---

pykeepass/__init__.py
pykeepass/attachment.py
pykeepass/baseelement.py
pykeepass/entry.py
pykeepass/group.py
pykeepass/kdbx_parsing/__init__.py
pykeepass/pykeepass.py

There is not much to say here except a little detail, if you already reviewed the PR you might notice that inside `entry.py` and `attachment.py` I use this syntax `from . import entry` this is to import from the current package a specific module.
This is to avoid what is called circular imports, (and similar strategy was in place before this one).
Also I added a variable used in `pykeepass.py` to the `__init__.py` in `kdbx_parsing` since importing from the subpackage would be easier.

Use relative imports

---

README.rst
pykeepass/kdbx_parsing/kdbx3.py
pykeepass/kdbx_parsing/kdbx4.py
pykeepass/pykeepass.py
tests/tests.py

Fixes: https://github.com/libkeepass/pykeepass/issues/359

Add decrypt option to decrypt body on demand

---

pykeepass/entry.py
pykeepass/group.py
tests/tests.py

Code changes:
- Add `index` property to Entry
- Add `move` method to Entry
- Add `_first_entry` property to Group
Explanation:
To move Entries around we need to remove and then insert at the desired index, the KDBX format makes it so that Entries and group info is all mixed, so we have to get the first element index to position correctly the Entries.
If you know a better method to get the index of the first entry I'll put it in.
What it does:
It moves entries around a group, pretty self explanatory, like the Keepass and KeepassXC functionality.

entry: move entries within a group

---

README.rst
pykeepass/kdbx_parsing/common.py
tests/tests.py

In order to prevent application to create temporary files, provide keyfile as bytes.
Fixes: https://github.com/libkeepass/pykeepass/issues/363

Allow keyfile to be passed as bytes

---

pykeepass/deprecated.py

The file does not have the executable bit set in its filesystem permissions and is not script-like (no `if __name__ == "__main__"` and no interesting side effects), so a shebang is not useful.

Remove shebang line from pykeepass/deprecated.py

---

pyproject.toml

Before:
```
$ python3 -m build
$  tar -tzf dist/pykeepass-4.0.7.tar.gz 
pykeepass-4.0.7/
pykeepass-4.0.7/LICENSE
pykeepass-4.0.7/MANIFEST.in
pykeepass-4.0.7/PKG-INFO
pykeepass-4.0.7/README.rst
pykeepass-4.0.7/pykeepass/
pykeepass-4.0.7/pykeepass/__init__.py
pykeepass-4.0.7/pykeepass/attachment.py
pykeepass-4.0.7/pykeepass/baseelement.py
pykeepass-4.0.7/pykeepass/blank_database.kdbx
pykeepass-4.0.7/pykeepass/deprecated.py
pykeepass-4.0.7/pykeepass/entry.py
pykeepass-4.0.7/pykeepass/exceptions.py
pykeepass-4.0.7/pykeepass/group.py
pykeepass-4.0.7/pykeepass/icons.py
pykeepass-4.0.7/pykeepass/pykeepass.py
pykeepass-4.0.7/pykeepass/version.py
pykeepass-4.0.7/pykeepass/xpath.py
pykeepass-4.0.7/pykeepass.egg-info/
pykeepass-4.0.7/pykeepass.egg-info/PKG-INFO …
```

Fix missing pykeepass.kdbx_parsing when built with modern tools

---

pykeepass/pykeepass.py

The ISO formatted string can be stored in multiple formats. Use the built-in datetime.isoformat() and datetime.fromisoformat() functions, which able to handle all variants.
Fixes: https://github.com/libkeepass/pykeepass/issues/382

Use built-in isoformat support

---

pykeepass/kdbx_parsing/common.py
tests/tests.py

In case a keyfile as BytesIO has been read before, the next read will be empty. We need to ensure that we are reading the data from the beginning.
Add seek to start to fix it.

Fix composite key computation for BytesIO

---

pykeepass/pykeepass.py
tests/tests.py

Hi I tried to fix the issue #384 and wrote a small test but I didn't mess with the test databases so I used `add_entry` and `delete_entry` to set up my testcase.
If a reference is broken the code will now just return `None` and won't raise an exception. I think this is better and can be caught easily by the caller of `deref`.

Return `None` if `deref` encouters a broken reference (fixes #384)

---

pykeepass/entry.py
tests/tests.py

Setting a property would call `_set_string_field` which by default would set the protected status of the attribute as `"True"`.
In order to verify in tests if a property is protected we add a private method `_is_property_protected` which shares the code with `is_custom_property_protected`.
Fixes: https://github.com/libkeepass/pykeepass/issues/376

entry: Do not set protected=True on setters

---

pykeepass/version.py
pyproject.toml

The package relies on `setuptools` to retrieve the package metadata version. However, this dependency is not included in `pyproject.toml`, leading to runtime errors, as described in issue #390.
Following the recommendation in the [`version.py`](https://github.com/libkeepass/pykeepass/blob/a2da6854af4c45487f6788fd693d921c26ca8eb5/pykeepass/version.py) module, the package will omit `pkg_resources.get_distribution` and instead utilize the built-in `importlib.metadata.version` method to retrieve the package version for Python version 3.8 and above.
For older Python versions (< 3.8), `setuptools` will be installed as a dependency.

Package metadata version retrieval fix.
